### PR TITLE
Buffer window

### PR DESCRIPTION
**Pull request by roberti42**
This PR introduce buffer window to deal with endianess.

### CODE REVIEW

**Comment by roberti42** [comment]
> In the iterator end you dont check overflow in negative if the limit is bigger what happens?

could you point me to the code you're talking about?

**Comment by roberti42** [comment]
> adapt the test for the new code

which tests?

**Comment by roberti42** [comment]
>     1. In bitset constructor should be simpler, all this logic might be separated in  an inline function.
>     2. This tendency around the code to have big construtor. Function should be small and constructor smaller.
Ok

>     3. Try to think a way (in bitset) if it is possible to minimize the number of loops: where you use auto
Don't you think that this type of optimization should be left for the future? I think that we should concentrate on working code and stabilize the api, we could later ask run benchmark and avoid premature optimization.

>     4. Our bytebuffer are signed. Please do not assume in buffer window that is unsigned.
Which line are you refering?

>     5. size_t cannot less then zero is unsigned long in x64
I don't understand, could you please enter more details?

>     6. we need compos-ability something like
>        buffer_window stream{buffer}
Sure

**Comment by giorgiozoppi** [comment]
> > In the iterator end you dont check overflow in negative if the limit is bigger what happens?
> 
> could you point me to the code you're talking about?
later you changed. But before in the end() interator, you return something like
end() - _limit.

**Comment by giorgiozoppi** [comment]
Please just make compile and resolve comments, conflicts.

**Comment by roberti42** [comment]
> > adapt the test for the new code
> > which tests?
> > There are some commented tests..make dead commented code disappear

Removed the tests cause the read were moved from bytebuffer to buffer_window

**Comment by roberti42** [comment]
I made some changes. I also made a workaround to make travis happy.

> Here we should have to check the read error or size, return how many byte are read or -1 in case of errors, it is a standard way to check an error in system programming. **void return type is forbidden rule whenever we can return a result of a computation or a computation can fail**
> 
> ```
>  void read(util::bytebuffer& buf, pos_type position) {
>         pos_type cur = _file_input.tellg();
>         _file_input.seekg(position);
>         _file_input.read(&buf[0], buf.size());
>         read(buf);
>         _file_input.seekg(cur);
>     }
>     }
> ```

If i've not lost something, I think this is the only left. This is a "wont fix", I suggest that we will make a PR in the future to close the circle, when we will support reading from fstreams.

**Pull request merged**
